name: 🚀 Deploy website to cPanel

on:
  push:
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_PUB_SERVER }}
          username: ${{ secrets.FTP_PUB_USERNAME }}
          password: ${{ secrets.FTP_PUB_PASSWORD }}
          local-dir: docs/
          server-dir: /
